### ISSUE TITLE
No sound in GNOME 3.36 with .wav files

### ISSUE THREAD

**Issue by fabrixx** [nana-4/materia-sound-theme#1]
I edited in dconf publisher name-theme in Materia enabled sound-event and input-feedback-sound I copied the Materia folder in / usr / share / sounds. After restart I have no sounds. The default sounds of the freedesktop theme are not .wav but .oga. Could this be the problem? I have Arch Linux Gnome

**Comment by fabrixx** [comment]
i fixed by audacity conversion in ogg (and  updating symbolic links)
my article
https://www.osside.net/2020/05/howto-gnome-system-sound-theme-login-sound/

**Comment by nana-4** [comment]
Sorry for my late reply.

I also had this problem, so thanks for your tip! :+1:  This is a strange issue, though.

The freedesktop's [sound theme spec](http://0pointer.de/public/sound-theme-spec.html) says:

> The sounds files must be one of the types: WAV/PCM 8-48kHz, 8/16 bits or OGG/Vorbis I. The extension must be ".wav", or ".oga" respectively (in lower case). It is not recommended to use ".ogg" extension, but it is also supported for legacy reasons.

So `.wav` should really be available here. I suspect this is actually a bug in one of the GNOME components. Would be nice to report it upstream, once we find the actual offender...

**Comment by fabrixx** [comment]
In fact, I too had read the specifications and wav was supported, I kept
changing only the paths but still didn't read them.  I also think it
depends on Gnome or Arch Linux.  When I get home, I may file a report.  I
could try with KDE on virtual box.

Il gio 28 mag 2020, 10:22 nana-4 <notifications@github.com> ha scritto:

**Comment by nana-4** [comment]
I've confirmed .ogg works fine indeed, so replaced .wav with it for now ;)

**Comment by fabrixx** [comment]
Ok. As soon as I can I will also edit my article with link to github.


Il gio 28 mag 2020, 12:31 nana-4 <notifications@github.com> ha scritto:

**Comment by nana-4** [comment]
Although I searched for a while, I couldn't know where to report the bug.

Anyway it has been resolved on the theme side, so I'm going to close this issue.

**Comment by fabrixx** [comment]
Ok for me

Il sab 30 mag 2020, 09:11 nana-4 <notifications@github.com> ha scritto:
